apiVersion: v1
kind: Service
metadata:
  name: {{ include "jiro.fullname" . }}
  labels:
    app.kubernetes.io/name: jiro-search
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: jiro-search
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
